# Ques 7

In [1]:
def unique_list(l):
    x=[]
    for a in l:
        if a not in x:
            x.append(a)
    return x
print(unique_list([1,2,3,3,3,4,2,6]))

[1, 2, 3, 4, 6]


# Ques 4

In [2]:
def isAnagram(w1, w2):
    sw1=''.join(sorted(w1))
    sw2=''.join(sorted(w2))
    if(sw1==sw2):
        return True
    return False
isAnagram("evil","vile")

True

# Ques 3

In [3]:
def sum_numbers(*args):
    if type (args[0])==list:
        args= args[0]
    return sum(args)
print(sum_numbers(5,6,7,8,9))
print(sum_numbers([5,6,7,8,10]))

35
36


# Ques 5

In [4]:
import random

l=[]
for i in range(0,9):
    l.append(random.randrange(5,9))

print("List:"+ str(l))
freq={}
max_freq=0

for i in l:
    freq[i]= l.count(i)
    if freq[i]>max_freq:
        max_freq= freq[i]
        k=i

res_list = [i for i in range(len(l)) if l[i]==k]
    
print("Freq: "+str(freq))
print("Max_freq: "+str(max_freq))
print("Indices: "+str(res_list))

    

List:[5, 5, 6, 6, 8, 7, 7, 7, 5]
Freq: {5: 3, 6: 2, 8: 1, 7: 3}
Max_freq: 3
Indices: [0, 1, 8]


# Ques 6

In [5]:
import random

l1=[]
l2=[]

for i in range (0,10):
    l1.append(random.randrange(40,49))
for i in range (0,10):
    l2.append(random.randrange(41,48))

l3=[]
for i in range(len(l1)):
    if i%2==0:
        l3.append(l1[i])
for i in range(len(l2)):
    if(i%2==1):
        l3.append(l2[i])
print("List1: "+ str(l1))
print("List2: "+ str(l2))
print("List3: "+ str(l3))

List1: [44, 46, 42, 44, 47, 41, 44, 43, 43, 43]
List2: [44, 41, 41, 41, 45, 47, 44, 44, 44, 46]
List3: [44, 42, 47, 44, 43, 41, 41, 47, 44, 46]


# Ques 12

In [6]:
def returnSum(dict):
    return sum(dict.values())

dict= {'a':100, 'b':200, 'c':300}
print("Sum :",returnSum(dict))

Sum : 600


# Ques 10

In [7]:
def splitArr(arr,n,k):
    for i in range(0,k):
        x=arr[0]
        for j in range(0,n-1):
            arr[j]= arr[j+1]
        arr[n-1]=x

arr=[12,10,5,6,52,36]
print("Original: "+str(arr))
n= len(arr)
position= 2

splitArr(arr, n, position)
print("Rotated: "+str(arr))

Original: [12, 10, 5, 6, 52, 36]
Rotated: [5, 6, 52, 36, 12, 10]


# Ques 2

In [8]:
import numpy as np 
import pandas as pd
#(roll no, name, subject, age, marks)
data={
    "roll_no":[100,20,30,40,50,60,70,80,90,10],
    "name":["Dishant","Ritesh","Sahaj","Toshit","Vikas","Legend_Vimal","Vaibhav","Harsh","Yash","Shreyansh"],
    "subject":["os","ai","chemistry","physics","dbms","ml","eco","eco","eco","AI"],
    "age":[19,20,19,20,19,20,19,20,19,20],
    "marks":[100,99,98,97,96,95,94,93,92,91]
}
lables=[1,2,3,4,5,6,7,8,9,10]
df=pd.DataFrame(data,index=lables)
print(df)
print("\nMax: ",df.max())
print("\nMin: ",df.min())
print("\nMean: ",df.mean())
print("\nMedian: ",df.median())
print("\nStd: ",df.std())

    roll_no          name    subject  age  marks
1       100       Dishant         os   19    100
2        20        Ritesh         ai   20     99
3        30         Sahaj  chemistry   19     98
4        40        Toshit    physics   20     97
5        50         Vikas       dbms   19     96
6        60  Legend_Vimal         ml   20     95
7        70       Vaibhav        eco   19     94
8        80         Harsh        eco   20     93
9        90          Yash        eco   19     92
10       10     Shreyansh         AI   20     91

Max:  roll_no        100
name          Yash
subject    physics
age             20
marks          100
dtype: object

Min:  roll_no         10
name       Dishant
subject         AI
age             19
marks           91
dtype: object

Mean:  roll_no    55.0
age        19.5
marks      95.5
dtype: float64

Median:  roll_no    55.0
age        19.5
marks      95.5
dtype: float64

Std:  roll_no    30.276504
age         0.527046
marks       3.027650
dtype: float64


C:\Users\atuls\AppData\Local\Temp\ipykernel_29900\3221100217.py:16: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nMean: ",df.mean())
C:\Users\atuls\AppData\Local\Temp\ipykernel_29900\3221100217.py:17: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nMedian: ",df.median())
C:\Users\atuls\AppData\Local\Temp\ipykernel_29900\3221100217.py:18: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is dep

# Ques 8

In [9]:
import numpy as np

a=np.random.rand(20,5)
print("Original array: "+ str(a))
b=a[:10,:]
print()
print("Extracted array: "+ str(b))

Original array: [[0.96801761 0.16133268 0.22277518 0.10150805 0.6756199 ]
 [0.45780268 0.18366962 0.97271636 0.76860216 0.20940803]
 [0.74806091 0.39165889 0.09170899 0.85294243 0.69382709]
 [0.54752947 0.24714045 0.330841   0.52605962 0.65999658]
 [0.34491067 0.16357825 0.0390404  0.94277634 0.39158229]
 [0.3323944  0.64659585 0.88065548 0.15708745 0.1657372 ]
 [0.70792188 0.20050735 0.77084545 0.00805046 0.11665817]
 [0.75017443 0.36412986 0.03852674 0.05511071 0.84995681]
 [0.62002757 0.70439957 0.7192131  0.66470823 0.37894282]
 [0.70537574 0.76080437 0.56339679 0.16679492 0.8302896 ]
 [0.25635518 0.04854597 0.17404928 0.82936514 0.31859449]
 [0.92336304 0.76844416 0.89960039 0.92641705 0.10258019]
 [0.87538995 0.5832247  0.86338475 0.39914946 0.26534345]
 [0.70282744 0.64932148 0.03340084 0.17130797 0.86161634]
 [0.83543584 0.38520963 0.43755342 0.52642197 0.74549933]
 [0.39193615 0.08794452 0.94466045 0.78222838 0.83616824]
 [0.47473115 0.86613112 0.40301919 0.7473944  0.42064234

# Ques 9

In [10]:
import re
def pos_neg_sum(str1):
    pos_values= sum(int(n) for n in re.findall('\d+',str1))
    neg_values= sum(int(n) for n in re.findall('-\d+',str1))
    return pos_values, neg_values

str1= '-100#^sdfkj8902w3ir021@swf-20'
print("String: "+ str(str1))
result= pos_neg_sum(str1)

print("Pos sum: ", result[0])
print("Neg sum: ", result[1])

String: -100#^sdfkj8902w3ir021@swf-20
Pos sum:  9046
Neg sum:  -120


# Ques 11

In [11]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

print("Transpose: ")
print(arr.transpose())
print("Flatten: ")
print(arr.flatten())


[[1 2 3]
 [4 5 6]]
Transpose: 
[[1 4]
 [2 5]
 [3 6]]
Flatten: 
[1 2 3 4 5 6]
